FROM plantuml/plantuml-server:tomcat

RUN apt update -y
RUN apt upgrade -y
RUN apt install \
  git \
  curl \
  vim \
  -y 

# Github CLI
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
RUN apt update
RUN apt install gh

RUN useradd -m plantuml

USER plantuml
