version: "3.9"
services:
  project:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    container_name: sumer-project
    working_dir: /usr/src/app/project
    volumes:
      - ..:/usr/src/app/project
