@startuml Factory Pattern
!include theme.puml
title Factory Pattern

interface IButton {
  - string render_template 
  + string render() 
}

class HtmlButton implements IButton {}

class WindowsButton implements IButton {}

interface IDialogBox {
  - string render_template 
  + string render()
  + void createButton() 
}

class WindowsDialogBox implements IDialogBox {}
class HtmlDialogBox implements IDialogBox {}

IDialogBox .> IButton

HtmlDialogBox -> HtmlButton
WindowsDialogBox -> WindowsButton

@enduml
